server:
  port: 8081
#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#Banner Mode we can set up 3 types
# OFF, LOG, CONSOLE
spring:
  banner:
    location: banner2.txt
  main:
    banner-mode: CONSOLE
  datasource:
    url: jdbc:mysql://localhost:3306/web_student_tracker
    username: webstudent
    password: webstudent123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    spring.jpa.database-platform: org.hibernate.dialect.MySQLDialect
  h2:
    console.enabled: true
# Changing the Banner in Spring application

